#!/usr/bin/env bun
import { readdirSync, readFileSync, existsSync, writeFileSync, mkdirSync, statSync } from "node:fs";
import { join, dirname } from "node:path";

type Event = { type: string; phase?: string; skill?: string; sessionId?: string };

type IssueSample = {
  issueId: string;
  skillRequired: number;
  skillSatisfied: number;
  skillAckMissing: number;
  identityReadCount: number;
  hasIdentityRead: boolean;
};

type Report = {
  rootScanned: string;
  sample: number;
  sampledIssues: IssueSample[];
  totalSkillRequired: number;
  totalSkillSatisfied: number;
  skillAckMissingRate: number;
  identityReadMissingRate: number;
  generatedAt: string;
};

function parseArgs(argv: string[]): { root: string; sample: number; out: string } {
  let root = process.cwd();
  let sample = 10;
  let out = join("docs", "audits", "GXPM-187-bootstrap-baseline.md");
  const requireValue = (flag: string, i: number): string => {
    if (i + 1 >= argv.length) {
      throw new Error(`flag ${flag} requires a value`);
    }
    return argv[i + 1];
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--root") {
      root = requireValue("--root", i);
      i++;
    } else if (a === "--sample") {
      const raw = requireValue("--sample", i);
      const n = Number(raw);
      if (!Number.isFinite(n) || n <= 0) {
        throw new Error(`--sample must be a positive number, got ${JSON.stringify(raw)}`);
      }
      sample = n;
      i++;
    } else if (a === "--out") {
      out = requireValue("--out", i);
      i++;
    }
  }
  return { root, sample, out };
}

function readEvents(path: string): Event[] {
  if (!existsSync(path)) return [];
  const raw = readFileSync(path, "utf8");
  const out: Event[] = [];
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    try {
      out.push(JSON.parse(trimmed) as Event);
    } catch {
      // skip malformed line
    }
  }
  return out;
}

function summarizeIssue(issueId: string, events: Event[]): IssueSample {
  let skillRequired = 0;
  let skillSatisfied = 0;
  let identityReadCount = 0;
  for (const e of events) {
    if (e.type === "skill.load.required") skillRequired++;
    else if (e.type === "skill.load.satisfied") skillSatisfied++;
    else if (e.type === "issue.context.read" || e.type === "worktree.identity.read") identityReadCount++;
  }
  return {
    issueId,
    skillRequired,
    skillSatisfied,
    skillAckMissing: Math.max(0, skillRequired - skillSatisfied),
    identityReadCount,
    hasIdentityRead: identityReadCount > 0,
  };
}

function pickSampleIssues(root: string, sample: number): string[] {
  const issuesDir = join(root, ".gxpm", "issues");
  if (!existsSync(issuesDir)) return [];
  const entries = readdirSync(issuesDir).filter((name) => {
    try {
      return statSync(join(issuesDir, name)).isDirectory();
    } catch {
      return false;
    }
  });
  entries.sort();
  return entries.slice(0, sample);
}

function renderMarkdown(report: Report): string {
  const skillPct = (report.skillAckMissingRate * 100).toFixed(1) + "%";
  const idPct = (report.identityReadMissingRate * 100).toFixed(1) + "%";
  const lines = [
    "# GXPM-187 Session Bootstrap Baseline Audit",
    "",
    `- Generated: ${report.generatedAt}`,
    `- Root scanned: \`${report.rootScanned}\``,
    `- Sample size: ${report.sample} issues`,
    "",
    "## Aggregate metrics",
    "",
    `- **skillAckMissingRate**: ${skillPct} (${report.totalSkillRequired - report.totalSkillSatisfied} of ${report.totalSkillRequired} required loads lack satisfied)`,
    `- **identityReadMissingRate**: ${idPct} (issues with zero identity-read events / sampled issues)`,
    "",
    "## Per-issue breakdown",
    "",
    "| Issue | skill.required | skill.satisfied | ack missing | identity reads |",
    "|---|---|---|---|---|",
  ];
  for (const s of report.sampledIssues) {
    lines.push(
      `| ${s.issueId} | ${s.skillRequired} | ${s.skillSatisfied} | ${s.skillAckMissing} | ${s.identityReadCount} |`,
    );
  }
  lines.push("", "## Source", "", "Generated by `scripts/audit-bootstrap-protocol.ts`.", "");
  return lines.join("\n");
}

export function auditBootstrapProtocol(opts: { root: string; sample: number }): Report {
  const issueIds = pickSampleIssues(opts.root, opts.sample);
  const sampled = issueIds.map((id) => {
    const events = readEvents(join(opts.root, ".gxpm", "issues", id, "events.jsonl"));
    return summarizeIssue(id, events);
  });
  const totalSkillRequired = sampled.reduce((acc, s) => acc + s.skillRequired, 0);
  const totalSkillSatisfied = sampled.reduce((acc, s) => acc + s.skillSatisfied, 0);
  const skillAckMissingRate = totalSkillRequired === 0 ? 0 : (totalSkillRequired - totalSkillSatisfied) / totalSkillRequired;
  const issuesWithoutIdentityRead = sampled.filter((s) => !s.hasIdentityRead).length;
  const identityReadMissingRate = sampled.length === 0 ? 0 : issuesWithoutIdentityRead / sampled.length;
  return {
    rootScanned: opts.root,
    sample: sampled.length,
    sampledIssues: sampled,
    totalSkillRequired,
    totalSkillSatisfied,
    skillAckMissingRate,
    identityReadMissingRate,
    generatedAt: new Date().toISOString(),
  };
}

if (import.meta.main) {
  const { root, sample, out } = parseArgs(process.argv.slice(2));
  const report = auditBootstrapProtocol({ root, sample });
  process.stdout.write(JSON.stringify(report, null, 2) + "\n");
  const outDir = dirname(out);
  if (outDir && !existsSync(outDir)) mkdirSync(outDir, { recursive: true });
  writeFileSync(out, renderMarkdown(report));
}
